export type InterclasseProduct = {
  id: string
  name: string
  slug: string
  price: number
  salePrice: number | null
  image: string
  files: number
  images: string[]
}

export const products: InterclasseProduct[] = [
  {
    id: "inter-01",
    name: "Completo 2025",
    slug: "pack-completo-interclasse-2025",
    price: 97.00,
    salePrice: 47.00,
    image: "/interclasse/488_Pantera 02.png",
    files: 33,
    images: ["/interclasse/488_Pantera 02.png"],
  },
  {
    id: "inter-02",
    name: "Pantera 488",
    slug: "pantera-488-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/488_Pantera 02.png",
    files: 6,
    images: ["/interclasse/488_Pantera 02.png"],
  },
  {
    id: "inter-03",
    name: "Fenix 445",
    slug: "fenix-445-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/445_Fenix 02.png",
    files: 6,
    images: ["/interclasse/445_Fenix 02.png"],
  },
  {
    id: "inter-04",
    name: "Dragão 291",
    slug: "dragao-291-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/291_Dragão 02.png",
    files: 6,
    images: ["/interclasse/291_Dragão 02.png"],
  },
  {
    id: "inter-05",
    name: "Dragão 306",
    slug: "dragao-306-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/306_Dragão 02.png",
    files: 6,
    images: ["/interclasse/306_Dragão 02.png"],
  },
  {
    id: "inter-06",
    name: "Tigre 839",
    slug: "tigre-839-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/839_Tigre 02.png",
    files: 6,
    images: ["/interclasse/839_Tigre 02.png"],
  },
  {
    id: "inter-07",
    name: "Tigre Bege 809",
    slug: "tigre-bege-809-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/809_Tigre Bege 02.png",
    files: 6,
    images: ["/interclasse/809_Tigre Bege 02.png"],
  },
  {
    id: "inter-08",
    name: "Águia 844",
    slug: "aguia-844-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/844_Aguia 02.png",
    files: 6,
    images: ["/interclasse/844_Aguia 02.png"],
  },
  {
    id: "inter-09",
    name: "Pokemon Gengar 800",
    slug: "pokemon-gengar-800-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/800_Pokemon Gengar 02.png",
    files: 6,
    images: ["/interclasse/800_Pokemon Gengar 02.png"],
  },
  {
    id: "inter-10",
    name: "Gengar Pokemon 842",
    slug: "gengar-pokemon-842-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/842_Gengar Pokemon 02.png",
    files: 6,
    images: ["/interclasse/842_Gengar Pokemon 02.png"],
  },
  {
    id: "inter-11",
    name: "Frozen 712",
    slug: "frozen-712-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/712_Frozen 02.png",
    files: 6,
    images: ["/interclasse/712_Frozen 02.png"],
  },
  {
    id: "inter-12",
    name: "Lilo e Stitch 834",
    slug: "lilo-stitch-834-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/834_Lilo e Stitch 02.png",
    files: 6,
    images: ["/interclasse/834_Lilo e Stitch 02.png"],
  },
  {
    id: "inter-13",
    name: "A Bela e a Fera 759",
    slug: "bela-fera-759-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/759_A Bela e a Fera 02.png",
    files: 6,
    images: ["/interclasse/759_A Bela e a Fera 02.png"],
  },
  {
    id: "inter-14",
    name: "Feiticeiro 832",
    slug: "feiticeiro-832-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/832_Feiticeiro 02.png",
    files: 6,
    images: ["/interclasse/832_Feiticeiro 02.png"],
  },
  {
    id: "inter-15",
    name: "Múmia 669",
    slug: "mumia-669-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/669_Mumia 02.png",
    files: 6,
    images: ["/interclasse/669_Mumia 02.png"],
  },
  {
    id: "inter-16",
    name: "Japão 308",
    slug: "japao-308-interclasse",
    price: 14.90,
    salePrice: 9.90,
    image: "/interclasse/308_Japão 02.png",
    files: 6,
    images: ["/interclasse/308_Japão 02.png"],
  },
  {
    id: "inter-17",
    name: "Dragoes",
    slug: "pack-dragoes-interclasse",
    price: 24.90,
    salePrice: 14.90,
    image: "/interclasse/291_Dragão 02.png",
    files: 12,
    images: ["/interclasse/291_Dragão 02.png", "/interclasse/306_Dragão 02.png"],
  },
  {
    id: "inter-18",
    name: "Gengar",
    slug: "pack-gengar-interclasse",
    price: 24.90,
    salePrice: 14.90,
    image: "/interclasse/800_Pokemon Gengar 02.png",
    files: 12,
    images: ["/interclasse/800_Pokemon Gengar 02.png", "/interclasse/842_Gengar Pokemon 02.png"],
  },
  {
    id: "inter-19",
    name: "Camisa Pantera",
    slug: "camisa-pantera",
    price: 29.90,
    salePrice: 19.90,
    image: "/interclasse/488_Pantera 02.png",
    files: 8,
    images: ["/interclasse/488_Pantera 02.png"],
  },
  {
    id: "inter-20",
    name: "Camisa Fenix",
    slug: "camisa-fenix",
    price: 34.90,
    salePrice: 24.90,
    image: "/interclasse/445_Fenix 02.png",
    files: 6,
    images: ["/interclasse/445_Fenix 02.png"],
  },
  {
    id: "inter-21",
    name: "Camisa Tigre",
    slug: "camisa-tigre",
    price: 24.90,
    salePrice: 14.90,
    image: "/interclasse/839_Tigre 02.png",
    files: 6,
    images: ["/interclasse/839_Tigre 02.png"],
  },
  {
    id: "inter-22",
    name: "Camisa Dragão",
    slug: "camisa-dragao",
    price: 39.90,
    salePrice: null,
    image: "/interclasse/306_Dragão 02.png",
    files: 6,
    images: ["/interclasse/306_Dragão 02.png"],
  },
  {
    id: "inter-23",
    name: "Camisa Águia",
    slug: "camisa-aguia",
    price: 59.90,
    salePrice: 39.90,
    image: "/interclasse/844_Aguia 02.png",
    files: 12,
    images: ["/interclasse/844_Aguia 02.png"],
  },
]
