export type TerceiraoProduct = {
  id: string
  name: string
  slug: string
  price: number
  salePrice: number | null
  image: string
  files: number
  images: string[]
}

export const products: TerceiraoProduct[] = [
  {
    id: "ter-01",
    name: "Pack Completo Terceirão 2025",
    slug: "pack-completo-terceirao-2025",
    price: 97.00,
    salePrice: 47.00,
    image: "/interclasse/488_Pantera 02.png",
    files: 33,
    images: ["/interclasse/488_Pantera 02.png"],
  },
  {
    id: "ter-02",
    name: "Pantera 488",
    slug: "pantera-488-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/488_Pantera 02.png",
    files: 6,
    images: ["/interclasse/488_Pantera 02.png"],
  },
  {
    id: "ter-03",
    name: "Fenix 445",
    slug: "fenix-445-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/445_Fenix 02.png",
    files: 6,
    images: ["/interclasse/445_Fenix 02.png"],
  },
  {
    id: "ter-04",
    name: "Dragão 291",
    slug: "dragao-291-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/291_Dragão 02.png",
    files: 6,
    images: ["/interclasse/291_Dragão 02.png"],
  },
  {
    id: "ter-05",
    name: "Dragão 306",
    slug: "dragao-306-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/306_Dragão 02.png",
    files: 6,
    images: ["/interclasse/306_Dragão 02.png"],
  },
  {
    id: "ter-06",
    name: "Tigre 839",
    slug: "tigre-839-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/839_Tigre 02.png",
    files: 6,
    images: ["/interclasse/839_Tigre 02.png"],
  },
  {
    id: "ter-07",
    name: "Tigre Bege 809",
    slug: "tigre-bege-809-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/809_Tigre Bege 02.png",
    files: 6,
    images: ["/interclasse/809_Tigre Bege 02.png"],
  },
  {
    id: "ter-08",
    name: "Águia 844",
    slug: "aguia-844-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/844_Aguia 02.png",
    files: 6,
    images: ["/interclasse/844_Aguia 02.png"],
  },
  {
    id: "ter-09",
    name: "Pokemon Gengar 800",
    slug: "pokemon-gengar-800-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/800_Pokemon Gengar 02.png",
    files: 6,
    images: ["/interclasse/800_Pokemon Gengar 02.png"],
  },
  {
    id: "ter-10",
    name: "Gengar Pokemon 842",
    slug: "gengar-pokemon-842-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/842_Gengar Pokemon 02.png",
    files: 6,
    images: ["/interclasse/842_Gengar Pokemon 02.png"],
  },
  {
    id: "ter-11",
    name: "Frozen 712",
    slug: "frozen-712-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/712_Frozen 02.png",
    files: 6,
    images: ["/interclasse/712_Frozen 02.png"],
  },
  {
    id: "ter-12",
    name: "Lilo e Stitch 834",
    slug: "lilo-stitch-834-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/834_Lilo e Stitch 02.png",
    files: 6,
    images: ["/interclasse/834_Lilo e Stitch 02.png"],
  },
  {
    id: "ter-13",
    name: "A Bela e a Fera 759",
    slug: "bela-fera-759-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/759_A Bela e a Fera 02.png",
    files: 6,
    images: ["/interclasse/759_A Bela e a Fera 02.png"],
  },
  {
    id: "ter-14",
    name: "Feiticeiro 832",
    slug: "feiticeiro-832-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/832_Feiticeiro 02.png",
    files: 6,
    images: ["/interclasse/832_Feiticeiro 02.png"],
  },
  {
    id: "ter-15",
    name: "Múmia 669",
    slug: "mumia-669-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/669_Mumia 02.png",
    files: 6,
    images: ["/interclasse/669_Mumia 02.png"],
  },
  {
    id: "ter-16",
    name: "Japão 308",
    slug: "japao-308-terceirao",
    price: 19.90,
    salePrice: null,
    image: "/interclasse/308_Japão 02.png",
    files: 6,
    images: ["/interclasse/308_Japão 02.png"],
  },
]
